### ISSUE TITLE
Pathfinder / Transition state search in xtb

### ISSUE THREAD

**Issue by Dnasiul** [grimme-lab/xtb_docs#18]
Hello. I have some problems with the usage of $path on xcontrol. I believe that it is a nudget-elastic band calculation (or some similar algorithm). Could I respectfully ask you to extend the corresponding information on this topic here, maybe with some example?

**Comment by awvwgk** [comment]
The pathfinder in `xtb` is based on [S. Grimme, *J. Chem. Theory Comput.*, **2019**, 155, 2847-2862](https://dx.doi.org/10.1021/acs.jctc.9b00143). Also have a look at the [GSM](https://xtb-docs.readthedocs.io/en/latest/gsm.html) interfaced to `xtb`.

**Comment by Dnasiul** [comment]
Excellent. Thanks!
