### ISSUE TITLE
gbsa with benzene and gfn2

### ISSUE THREAD

**Issue by tobigithub** [grimme-lab/xtb_docs#25]
The  [xtb1](https://github.com/grimme-lab/xtb/blob/7a0623f8059859f0740f2ca5c1e2df0d3fd09542/man/man1/xtb.1.txt) definition states that gbsa with  'benzene' is (only GFN1-xTB),

However the WIKI https://xtb-docs.readthedocs.io/en/latest/gbsa.html#parameterized-solvents states that benzene is also available for gfn2

````
solvents | GFN1 | GFN2
-- | -- | --
Acetone | x | x
Acetonitrile | x | x
Benzene | x | x
````

However executing 
````
xtb aniline.xyz --opt extreme --gbsa benzene 
 Solvent             : benzene
#ERROR! solvent : benzene not parametrized for GFN2-xTB Hamiltonian
abnormal termination of xtb
````
using gfn1 it works as expected
````
 xtb aniline.xyz --opt extreme --gbsa benzene  --gfn1
normal termination of xtb
````

**Solution**: either parameterize benzene for gfn2 or change wiki

**Comment by awvwgk** [comment]
This was just added recently with 49862bc9f842f06100d484491bb9eefefa361083 and the docs are more current than the latest binary distribution right now.

**Comment by awvwgk** [comment]
Also the benzene parameters happen to be the toluene parameters for both GFN1-xTB and GFN2-xTB. This is totally fine because the dielectric constants are similar and there is no need for a separate parametrisation for both solvents.

**Comment by tobigithub** [comment]
OK, so its an enhancement once it calculates.

However, the [Hansen solubility parameters](https://en.wikipedia.org/wiki/Hansen_solubility_parameter) are different for benzene and toluene,
so there must be differences. Didn't check COSMO-RS/COSMOTherm, 
probably similar differences. 

````
| Solvents | dD   | dP  | dH | MVol  |
|----------|------|-----|----|-------|
| Benzene  | 18.4 | 0   | 2  | 52.9  |
| Toluene  | 18   | 1.4 | 2  | 106.6 |

dD: The energy from dispersion forces between molecules
dP: The energy from dipolar intermolecular force between molecules
dH: The energy from hydrogen bonds between molecules.
`````
For example the solubilities for fullerenes C60 and C70 are different
in benzene and toluene (Ref: [WIKI](https://en.wikipedia.org/wiki/Solubility_of_fullerenes)) so there are quite some differences.

````
|         |Sol [g/l]|Sol [g/l]|
|---------|---------|---------|
| Solvent | C60     | C70     |
|---------|---------|---------|
| toluene | 3       | 1.406   |
| benzene | 1.5     | 1.3     |

````

Plus this, an interesting read:
Benzene Dimer:  A Good Model for π−π Interactions in Proteins? A Comparison between the Benzene and the Toluene Dimers in the Gas Phase and in an Aqueous Solution [[LINK]](https://pubs.acs.org/doi/abs/10.1021/ja961379)

**Comment by awvwgk** [comment]
@tobigithub Please keep in mind we are talking about a semiempirical method here. I doubt we are able to resolve the the difference in solubility (which aren't that simple to calculate by themselves) with a simple generalized Born model together with a tight binding method. The GBSA as implemented will even have implicit solvent *inside* the fullerene, because we can't account for the topology of the system.

**Comment by tobigithub** [comment]
Agree, I did not now about the level of accuracy.
T.
