### ISSUE TITLE
xtb and Turbomole

### ISSUE THREAD

**Issue by mhrmsn** [grimme-lab/xtb_docs#27]
I think Turbomole can be added to the list of quantum chemistry programs that are interfaced to xtb. It's available in version 7.4.1.

**Comment by awvwgk** [comment]
Turbomole support was always native in `xtb`, with the `--grad` flag the printout is `jobex` compatible. The only minor issue is to get the `control` file for `statpt`.

**Comment by mhrmsn** [comment]
Yes, I was referring to the possibility of running xtb directly from within Turbomole now by setting `$tb` in the control file and running `jobex -level xtb` (which might be slightly more convenient in some cases). I think this was added in Turbomole 7.4 and is documented in the 7.4.1 manual.
