### ISSUE TITLE
CREST ensemble entropies ~9.1344 J/mol•k

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/xtb_docs#28]
**Describe the bug**
This would seem to be a bug with CREST rather than xtb, but there's no repo for that, and it might also relate to the GFN2 energy levels.

I've been looking at the computed ensemble entropies from CREST and they seem somewhat high. If I take a simple set of branching alkanes (i.e., adding free rotor CH3 groups)

- methane = 0.0 J/mol•K (**correct** - no conformers, all entropy should be vib / rot / translational)
- ethane = 9.134 J/mol•K ?
- propane = 18.269 J/mol•K (exactly double)
- iso-butane = 27.403 J/mol•K (triple)
- neo-pentane = 36.538 J/mol•K (4x)

**To Reproduce**
Steps to reproduce the behaviour: Run any of the attached xyz files with default CREST options.

[crest-issue.tar.gz](https://github.com/grimme-lab/xtb/files/4172220/crest-issue.tar.gz)

**Expected behaviour**

Since ethane, propane, butane have freely rotatable bonds, shouldn't the entropy scale with the gas constant (i.e., 8.314.. J/mol•K)?

**Comment by awvwgk** [comment]
I moved this over to the documentation repo, since it seems more concerned with documenting the actual behaviour of the program in question, rather than the program itself.

**Comment by ghutchis** [comment]
I'll send over a preprint - probably sometime next week. We've used CREST to explore conformational entropies across ~150k molecules with some very interesting results.
