### ISSUE TITLE
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.

### ISSUE THREAD

**Issue by adpressa** [grimme-lab/xtb_docs#37]
I receive the error in the title and below any time I try and run a -hess job. 

OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.

xtb was installed via conda (conda install xtb) and my current environment is:

name: xtb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1004
  - certifi=2020.6.20=py38h32f6830_0
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.65.0=h6f030ca_0
  - icu=67.1=he1b5a44_0
  - ld_impl_linux-64=2.34=h53a641e_5
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1006
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h72b56ed_1
  - ncurses=6.1=hf484d3e_1002
  - openbabel=3.1.1=py38hf4b5c11_0
  - openssl=1.1.1g=h516909a_0
  - pcre=8.44=he1b5a44_0
  - pip=20.1.1=py_1
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h14c3975_1001
  - python=3.8.3=cpython_he5300dc_0
  - python_abi=3.8=1_cp38
  - readline=8.0=hf8c457e_0
  - setuptools=47.3.1=py38h32f6830_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - wheel=0.34.2=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006

Any suggestions on how to correct this problem? Thanks in advance.

**Comment by awvwgk** [comment]
This is an issue for the conda-forge feedstock, not the documentation. Please [open an issue at the feedstock repository](https://github.com/conda-forge/xtb-feedstock/issues/new/choose) and follow the instructions in the template to provide a full report.

I will close this issue here in the meantime.
