### ISSUE TITLE
xTB in Other Quantum Chemistry Programs

### ISSUE THREAD

**Issue by ltalirz** [grimme-lab/xtb_docs#43]
https://xtb-docs.readthedocs.io/en/latest/contents.html#xtb-in-other-quantum-chemistry-programs

cp2k has an xtb implementation since version 7.1
https://www.cp2k.org/version_history

**Comment by awvwgk** [comment]
Thanks for the info. Feel free to open a PR to add it to the main page.

**Comment by maburs** [comment]
Thank you very much for this hint, I added CP2K to the list of codes with xtb implementations.
