### ISSUE TITLE
ERROR of pbc of xtb6.3.2

### ISSUE THREAD

**Issue by sbkk000** [grimme-lab/xtb_docs#53]
Dear xTB developer:
Thank you very much for taking the time to read my error.
I want to use the pbc of xtb6.3.2. 
According to the instructions of the help document, I created a "coord" file 

_$periodic 3 
$cell angs 
    3.570    3.570    3.570  90  90  90 
$coord angs 
  0.00000  0.00000  0.00000  C 
  0.89250  0.89250  0.89250  C 
  1.78500  1.78500  0.00000  C 
  2.67750  2.67750  0.89250  C 
  1.78500  0.00000  1.78500  C 
  2.67750  0.89250  2.67750  C 
  0.00000  1.78500  1.78500  C 
  0.89250  2.67750  2.67750  C 
$end_ 

and entered the following command:

_xtb coord_

Error information shows as follows:

_[ERROR] Program stopped due to fatal error
-3- Single point calculation terminated
-2- xtb_calculator_singlepoint: Electronic structure method terminated
-1- scf: Multipoles not available with PBC_
_abnormal termination of xtb_

I want to know if my input command is correct?
And if I want to do pbc structural optimization and molecular dynamics, can I directly add the following contents to the "coord" file?

_$periodic 3 
$cell angs 
    3.570    3.570    3.570  90  90  90 
$coord angs 
  0.00000  0.00000  0.00000  C 
  0.89250  0.89250  0.89250  C 
  1.78500  1.78500  0.00000  C 
  2.67750  2.67750  0.89250  C 
  1.78500  0.00000  1.78500  C 
  2.67750  0.89250  2.67750  C 
  0.00000  1.78500  1.78500  C 
  0.89250  2.67750  2.67750  C 
**$opt 
   engine=inertial** 
$end_ 

What should I do to solve this problem?

Looking forward to your reply, thanks~

**Comment by awvwgk** [comment]
The problem is described in clear text in the error message, there are no multipoles available for PBCs, which means you can't use the default GFN2-xTB model but have to select a different one.

**Comment by awvwgk** [comment]
Duplicate of https://github.com/grimme-lab/xtb/issues/354

**Comment by sbkk000** [comment]
Ok, thank you very much for your answer. 
I can use xtb semi-empirical method in cp2k, so what kind of force field is used in cp2k?

**Comment by awvwgk** [comment]
CP2K has a periodic GFN1-xTB implementation, which is also available in `xtb` by using the `--gfn 1` option.

**Comment by sbkk000** [comment]
Got it, thanks a lot
closing this issue
