### ISSUE TITLE
GBSA solvents

### ISSUE THREAD

**Issue by ikalvet** [grimme-lab/xtb_docs#6]
Could you please include the list of solvent names as they are accepted by XTB in the documentation.
I have tested them in XTB Version 6.1 beta, and saw that 'water' is not an accepted solvent name, only 'h2o' is. Also, 'n-Hexan' has to be written as 'nhexan' to be accepted. Of course no capital letters are also accepted. While most people can figure these things out through trial and error I see no reason why it shouldn't be documented.

**Comment by awvwgk** [comment]
The keywords given in the documentation are accepted in the 6.1 release version but were not in the beta version. An update of your local xtb version should fix this issue, therefore, I will close this issue. Sorry for the inconvenience.
